### ISSUE TITLE
Design files?

### ISSUE THREAD

**Issue by samuk** [robotdoly/DOLY-DIY#4]
Hi Nice project!

I see you have some Gerbers published, do you intend to publish the design files too so that you can use the OSHW logo etc?

I guess you're aware of this project https://www.pcbway.com/project/shareproject/Pi_MX8M_Plus_SoM_e3fe3cd9.html so an Open hardware CM4 should be available soon.

**Comment by robotdoly** [comment]
Hi there, thanks for your interest. I am planning to publish design files asap. Good to hear a new RPi CM4 compatible board is coming 👍

**Comment by samuk** [comment]
Great, do you plan to use a licence that complies with https://www.oshwa.org/definition?

**Comment by robotdoly** [comment]
Not today 👍

**Comment by samuk** [comment]
Tomorrow?

**Comment by samuk** [comment]
I'm unclear why you have closed this issue as 'completed' when the issue is not complete?

I also notice you've deleted my comments on Twitter that draw attention to the lack of design files.

If you don't want to be an open hardware project then that is fine, you're under no obligation to release design files.

I do think in that case you should stop describing this project as 'Open Hardware' as that is clearly not the case.

**Comment by robotdoly** [comment]
Regarding the issue being marked as 'completed,' I acknowledge that this was done prematurely. As this project is still in development, there are elements, including the sharing of design files, that are yet to be finalized. This is a beta test section just for a few friends! Please don't take it serious.

Concerning your comments on Twitter, I opted to hide them because they seemed to accuse me of not fulfilling a commitment that has not yet come due. As stated on my website's open-source section at [doly.ai/open-source](https://doly.ai/opensource/),  is clearly saying as 'coming soon.' I am committed to being transparent and upholding my promises, but it's important to note that this is a future endeavor, not a current omission. I am a bit perplexed by the aggressive tone in your approach regarding this matter, especially since I have clearly communicated my intentions on my website.

I understand your point about the term 'Open Hardware.' I want to clarify that I am not using this in the strict sense of Open Source Hardware (OSHW), which has specific criteria including the release of design files. The plan to release these files is still in place, but as a solo maker, it takes time to prepare these files for public release.

Your feedback is essential, and I am taking it seriously. Going forward, I will strive to communicate more clearly to avoid any misunderstandings. I appreciate your patience and understanding as I navigate the complexities of bringing this project to fruition.

If you have further questions or need additional clarification, please feel free to reach out.

**Comment by samuk** [comment]
![open-design](https://github.com/robotdoly/DOLY-DIY/assets/400875/f6f27f47-f1b8-429f-95ca-d4996c3795a0)

I do appreciate it takes a bit of time to upload files: https://github.com/rosmo-robot honestly it's a few seconds to export from your EDA program, a few seconds to upload it to Github. Documentation obviously takes longer.

The simple solution is for you to stop using the term 'open hardware' until your hardware is in fact open hardware.

I was irritated by your marketing because I got quite excited about your project, shared it on various Discord channels and networks I'm on, I even started work on a Mikroe expansion header for the back of your bot. At that point I realised you weren't actually a open hardware project at all.

It wasted my time and made me feel stupid. That's why I'm irritated.

**Comment by robotdoly** [comment]
Thank you for reaching out and sharing your perspective. I deeply appreciate your enthusiasm for the project and am sorry for any frustration or inconvenience caused.

Regarding the upload of design files, I want to reassure you that it is a priority, and I will be uploading them as soon as possible. However, as I have mentioned before, preparing these files for public use, ensuring their accuracy and completeness, does take time. It is not about export and upload, there are some points to that have to be revised.

I would like to clarify that I am not withholding information; if you need specific details or files, I am more than willing to share them with you directly. This is not a secret nor a significant issue. In fact, all schematics have already been uploaded.

I am dedicated to ensuring that this project meets the expectations associated with the term 'open hardware,' while not strictly adhering to the requirements set by the Open Source Hardware Association (OSHW). The OSHWA license has a distinct approach, particularly concerning commercial usage. Meanwhile, I request that you kindly disregard the current state of the repository.

Your support and the work you've begun, like the development of the Mikroe expansion header, are incredibly valuable. I am genuinely excited about the possibility of collaborating and incorporating your contributions into the project.

Once again, I apologize for any misunderstanding and the impact it has had. Your feedback is crucial, and I am committed to improving our communication and delivering on the project's promises.

Please feel free to reach out if you have any more concerns, need specific files, or have suggestions. Your ongoing support and understanding mean a lot to me.

**Comment by samuk** [comment]
Any news on when you're going to publish these files?

**Comment by robotdoly** [comment]
Let me share in a minute. As I mentioned before, still no documentation.

**Comment by robotdoly** [comment]
I placed the missing files under PCB folder. You can import them via EasyEDA. 

PCB_PCB_Doly_CE_2302.json
PCB_PCB_Doly_CE_Bumper_2210.json
PCB_PCB_Doly_CE_Head_2212.json 
PCB_PCB_Encoder 0922.json
PCB_Doly_Arm.json
SCH_DOLY_CE_ARM.json
SCH_Doly_CE_Bumper_v1.2210.json
SCH_Doly_CE_Encoder_0922.json
SCH_Doly_CE_Head_v1.2212.json
SCH_Doly_CE_v1.2302.json
